site_name: VideoOS open
repo_url: https://github.com/VideoOS/VideoOS
markdown_extensions:
  - admonition
nav:
  - '简介': 'index.md'
  - 'iOS SDK': 'iOS-SDK.md'
  - 'Android SDK': 'Android-SDK.md'
  - '控制台操作手册': 'manual.md'
  - '下载': 'download.md'
  - 'DEMO': 'demo.md'
  - '老版本': 'oldversion.md'