site_name: VideoOS open
repo_url: https://github.com/VideoOS/VideoOS
markdown_extensions:
  - admonition
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
extra_javascript:
  - javascript/anchor.js
nav:
  - 'VideoOS open介绍': 'index.md'
  - '流量主服务':
    - '注册与起步': 'get-started.md'
    - '视频广告变现': 'asmp.md'
    - '视频小程序': 'lua-app.md'
    - 'AI云': 'vod.md'
    - '下载 DEMO APP': 'demo.md'
  - '开发者服务':
    - '快速开始': 'devdoc/getting-started/getting-started.md'
    - '开发框架': 'devdoc/frame/overview.md'
    - 'Lua语言': 'http://docs.videojj.com/docs/videoos-lua-app'
    - 'JsonSchema': 'jsonschema.md'
